const
  // Common constants in the XML tree.
  rsName = 'Name';
  rsId   = 'id';
  rsType = 'Type';

  rsEpiData         = 'EpiData';
   // Settings
   rsSettings        = 'Settings';
    rsVersion         = 'Version';
    rsScrambled       = 'Scrambled';
    rsDateSep         = 'DateSeparator';
    rsDecSep          = 'DecimalSeparator';
    rsMissingStr      = 'MissingString';

   rsAdmin           = 'Admin';
    // User
    rsUsers           = 'Users';
     rsUser            = 'User';
      rsLogin           = 'Login';
      rsPassword        = 'Password';
      rsMasterPassword  = 'MasterPassword';
      rsLastLogin       = 'LastLogin';
      rsExpireDate      = 'ExpireDate';
      rsGroupId         = 'GroupId';

      // Group
    rsGroups          = 'Groups';
     rsGroup           = 'Group';
      rsRights          = 'Rights';

   rsStudy           = 'Study';
    rsProtocol        = 'Protocol';
    rsAbstract        = 'Abstract';
    rsAuthor          = 'Author';
    rsOwner           = 'Owner';
    rsCreated         = 'Created';
    rsCreator         = 'Creator';
    rsDescription     = 'Description';
    rsLanguage        = 'Language';
    rsModified        = 'Modified';
    rsProvenance      = 'Provenance';
    rsReferences      = 'References';
    rsRightsholder    = 'Rightsholder';
    rsSource          = 'Source';
    rsSubject         = 'Subject';
    rsTemporal        = 'Temporal';
    rsTitle           = 'Title';

   rsDataFiles       = 'DataFiles';
    rsEpiDataFiles    = 'EpiDataFiles';
     rsEpiDataFile     = 'EpiDataFile';
      rsValueLabels     = 'ValueLabels';
       rsValueLabel      = 'ValueLabel';
        rsInternal        = 'Internal';
         rsSet             = 'Set';
        rsExternal        = 'External';
         rsFile            = 'File';
         rsDataFileId      = 'DataFileId';
         rsValueField      = 'ValueField';
         rsLabelField      = 'LabelField';
      rsScreenInfo      = 'ScreenInfo';
      rsHeadings        = 'Headings';
      rsFields          = 'Fields';
       rsField           = 'Field';
      rsRecords         = 'Records';

   rsRelates         = 'Relates';

