name: Build Core Artifact

on:
  push:
    branches:
      - master

env:
  CORE_VERSION: "4.6"

jobs:
  setup:
    name: Checkout Source
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  build:
    name: Building the artifact
    runs-on: self-hosted
    container:
      image: epidata/fpcbuild:3.2.0-12
      volumes:
        - /etc/maven/settings.xml:/etc/maven/settings.xml
    needs: setup

    steps:
      - name: Compile Linux
        run: |
          mvn compile -Plinux64,core
          mvn compile -Plinux64,visuals

      - name: Compile Windows
        run: |
          mvn compile -Pwin64,core
          mvn compile -Pwin64,visuals

      - name: Compile Mac
        run: |
          mvn compile -Pdarwin64,core
          mvn compile -Pdarwin64,visuals

  deploy:
    name: Deploy Artifact
    runs-on: self-hosted
    needs: build

    steps:
      - name: Deploy
        run: |
          mvn versions:set -DnewVersion=${CORE_VERSION}.${GITHUB_RUN_NUMBER} -f deploy.pom.xml
          mvn deploy -f deploy.pom.xml
          mvn clean
