name: Build Core Artifact

on:
  push:
    branches:
      - master

env:
  CORE_VERSION: "1.1"

jobs:
  setup:
    name: Compile Core
    runs-on: ubuntu-latest
    container:
      image: epidata/fpcbuild:3.2.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          output_file: "/etc/maven/settings.xml"
          servers:
            '[{
            "id": "github",
            "username": "${{ secrets.CI_USER }}",
            "password": "${{ secrets.CI_PASSWORD }}"
            }]'
          repositories:
            '[
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/epidata-dk/parent/",
                "snapshots": {
                  "enabled": "true"
                }                
              }
            ]'

      - name: Compile Linux
        run: |
          mvn compile -Plinux64,core
          mvn compile -Plinux64,visuals

      - name: Compile Windows
        run: |
          mvn compile -Pwin64,core
          mvn compile -Pwin64,visuals

      - name: Compile Mac
        run: |
          mvn compile -Pdarwin64,core
          mvn compile -Pdarwin64,visuals

      - name: Deploy
        run: |
          mvn versions:set -DnewVersion=${CORE_VERSION}.${GITHUB_RUN_NUMBER} -f deploy.pom.xml
          mvn deploy -f deploy.pom.xml
          mvn clean
